name: Build all artifacts

on:
#  push:
#    branches: [ main ]
#    tags-ignore:
#      - 'v*.*.*.*' # v0.0.0.0
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  workflow_call:
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Install Lazarus (FPC)
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "stable"
        with-cache: true    
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make
      run: lazbuild GMegaSena.lpi
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gmegasena-linux-x64-bin
        path: GMegaSena

  build-windows-x64:
    runs-on: windows-latest
    steps:
    - name: Install Lazarus (FPC)
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "dist"
        with-cache: false    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      run: lazbuild GMegaSena.lpi
    - name: Upload artifact (64bits)
      uses: actions/upload-artifact@v3
      with:
        name: gmegasena-windows-x64-bin
        path: GMegaSena.exe        

  build-mac-x86_64:
    runs-on: macos-latest
    steps:
    - name: Install Lazarus (FPC)
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "stable"
        with-cache: true    
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make
      run: lazbuild --ws=cocoa GMegaSena.lpi
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gmegasena-mac-x86_64-bin
        path: GMegaSena*        
